version: '3.8'

services:
  backend:
    container_name: openmanus-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn run_api:app --host 0.0.0.0 --port 5172
    env_file:
      - .env

  web:
    container_name: openmanus-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web/keys:/app/keys:ro
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      - backend

networks:
  default:
    name: openmanus-network
